### ISSUE TITLE
port-forwarding-change-flag.py可以被绕过

### ISSUE THREAD

**Issue by ghost** [WangYihang/Attack_Defense_Framework#2]
port-forwarding-change-flag.py只检验了base64，但是可以被base32绕过，建议添加base32检查。

**Comment by WangYihang** [comment]
对的 , 关于如何检测 flag 被窃取确实是一个比较困难的问题 , 如果规则设置的多一些严格一些 , 就会非常影响性能 , 但是如果规则不全 , 就有可能被很轻易的绕过 , 就和 waf / 基于特征码的杀毒引擎 一样 , 不被绕过的前提就是对方不知道你是如何检测和过滤的 , 一旦被攻击者得知过滤规则 , 那么绕过就很容易了 , 这个问题确实很棘手 , 几乎不可能两全其美 , 所以只好先牺牲准确性了 , 本来这个框架只是内部使用 , 有些东西开源就失去了意义 , 哈哈 , 感谢关注

**Comment by ghost** [comment]
确实很容易绕过，后来发现很多绕过方法，最好的办法是把脚本藏好，当时比赛的时候你竟然把这个脚本放在了二进制程序目录下，幸亏我机（zhi）智（zhang）的看都没看就把它删了。非常感谢你的这些脚本，让我更了解线下赛，分常好的开源精神！

2017-11-29 16:02 GMT+08:00 王一航 <notifications@github.com>:

**Comment by WangYihang** [comment]
哈哈 是啊 比赛的时候我听到你们在说发现那个脚本了 我还以为你们直接把脚本下载下来在用 还挺心慌的 哈哈
这个脚本本来的写的逻辑是会生成 flag{[0-9][a-f]{32}} 这样的 flag 的 , 但是这次比赛的 flag 格式有点奇怪
当时忘记了改掉随机 flag 的生成逻辑了 被你们直接发现了 哈哈
做的更好一点就是能让随机生成的 flag 存活一段时间 , 最好是比赛的回合周期
还有一点就是及时删掉这个脚本 , 直接放在内存里面跑 , 别被别的队伍发现就好

不过这个还是有缺陷的 , 如果被别人发现有这个 python 脚本在跑的话 他们是有权限把这个进程结束掉的 这样题目直接就挂掉了 这个好像还真没办法解决
这次比赛的 pwn 题目部署的时候用了 socat , 而 socat 是直接在 user 这个用户下运行的 , 这样也是直接可以把别的队的题目直接
down 掉
或者更猥琐一点可以让 socat 新开一个端口监听 , 连上之后直接反弹一个 shell 或者直接 cat flag

在 2017年11月30日 上午2:21，1oner <notifications@github.com>写道：

**Comment by WangYihang** [comment]
这种线下竞赛更多比拼的是服务器的运维和思路的猥琐 , 类似的猥琐思路还有很多 , 以后可以整理整理 , 哈哈 , 一起加油吧

在 2017年11月30日 下午11:20，王一航 <wangyihanger@gmail.com>写道：

**Comment by ghost** [comment]
确实，毕竟ssh登陆的用户和运行二进制程序的用户是同一个，这次长见识了，感谢，加油吧。

2017-11-30 23:21 GMT+08:00 王一航 <notifications@github.com>:
