### ISSUE TITLE
Why heart broken?

### ISSUE THREAD

**Issue by summershrimp** [WangYihang/Attack_Defense_Framework#6]
ATT.

**Comment by WangYihang** [comment]
> Refers to: https://github.com/shadowsocks/shadowsocks


![image](https://user-images.githubusercontent.com/16917636/47199855-31e62b80-d3a6-11e8-926d-3e23a00a25ba.png)

**Comment by summershrimp** [comment]
hmmm... Some related department even care about CTF Tools?

**Comment by yonglaictf** [comment]
这不就是CTF工具吗怎么会被喝茶呢?难道是openvpn这几个字命中了啥规则...真神奇
